fix: add support for ADR74 emotes
decentraland/wearable-preview pull request #57
Opened 2022-09-12 20:04 UTC by cazala

Blocked by https://github.com/decentraland/common-schemas/pull/127

2022-09-13 17:01 UTC, cazala commented on src/lib/api/peer.ts
> +
This fetches an array of URNs and returns a list of wearables and a list of emotes from those urns

2022-09-13 19:51 UTC, cyaiox approved these changes

2022-09-13 20:37 UTC, LautaroPetaccio requested changes

2022-09-13 20:37 UTC, LautaroPetaccio commented on src/lib/config.ts
> +  return results
Just a suggestion (the async symbol can also be removed):
```suggestion
  return peerApi.fetchItems(urns, peerUrl)
```

2022-09-13 20:37 UTC, LautaroPetaccio commented on src/lib/config.ts
> +  return wearables as WearableDefinition[]
As you're casting what is being returned, can you assign it to the return type of the function? If not, the cast might seem redundant.

2022-09-13 20:41 UTC, cazala commented on src/lib/api/peer.ts
> +      })
afaik the catalyst client allows you to fetch by pointers but you always need to provide the entity type as well, which we don't know it beforehand.

2022-09-14 14:50 UTC, cazala commented
Applied feedback @LautaroPetaccio

2022-09-14 15:05 UTC, LautaroPetaccio approved these changes

2022-09-14 15:05 UTC, LautaroPetaccio commented on src/lib/api/peer.ts
> + * This converts representations into representation definitions. The difference is representations have contents: string[] and representation definitions have contents: { key: string, url: string}[]
```suggestion
 * Converts representations into representation definitions. Representations have contents as string[] and representation definitions have contents as { key: string, url: string}[].
```

2022-09-14 15:05 UTC, LautaroPetaccio commented on src/lib/api/peer.ts
> + * This converts an entity into a wearable or an emote definition
```suggestion
 * Converts an entity into a wearable or an emote definition.
```

2022-09-14 15:05 UTC, LautaroPetaccio commented on src/lib/api/peer.ts
> +   * @returns List of active entities for given pointers
```suggestion
  /**
   * Fetches the entities that represent the given pointers.
   * @param pointers List of pointers
   * @param peerUrl The url of a catalyst
   * @returns List of active entities for given pointers
```

2022-09-14 15:05 UTC, LautaroPetaccio commented on src/lib/api/peer.ts
> +   * @returns List of wearables and list of emotes for given urns
```suggestion
  /**
   * Fetches the entities represented by the given urns and processes them into Wearable and Emote definitions.
   * @param urns List of urns for wearables or emotes
   * @param peerUrl The url of a Catalyst
   * @returns List of wearables and list of emotes for given urns
```

2022-09-14 15:08 UTC, merged