feat: Add cylinder to scene to show animation boundaries
decentraland/wearable-preview pull request #61
Opened 2022-09-22 12:26 UTC by juanmahidalgo

2022-09-22 21:48 UTC, cyaiox approved these changes

2022-09-26 21:24 UTC, cazala requested changes
Could we add the new param to the README?

2022-09-26 22:43 UTC, cazala commented
Is the size of the cylinder correct according to current emotes? It looks like lots of them go out of bounds:

<img width="1047" alt="Screen Shot 2022-09-26 at 17 07 31" src="https://user-images.githubusercontent.com/2781777/192383487-2b12a03c-0a41-40f8-8169-a2a095a0d599.png">

Also, maybe I'm out of the loop since I wasn't part of this discussion, but what is the use of the ground? If the purpose is to know when the avatar goes below the ground level, I think it's not being very useful since it's not visible from below.. 

<img width="974" alt="Screen Shot 2022-09-26 at 17 10 18" src="https://user-images.githubusercontent.com/2781777/192383705-987435bb-7146-4272-9dd8-d45f7ec3df0a.png">

And from above I think is not really easy to fully know if the avatar is actually going below or not. The cylinder does work for this since it only extends from the ground level and above, so if the avatar goes below ground level you can see it outside of the volume of the cylinder, thus not tainted by the red color. Maybe it would be enough just to keep the cylinder? Or is there other use for the ground I'm not seeing?

2022-09-27 14:34 UTC, cazala approved these changes

2022-09-28 08:51 UTC, merged